/* GENERATED by tools/audio-check.cjs --write-calibration. Do not edit by hand.
 * Per cue and profile: `c` is the ceiling of the per-voice mastering shaper c·tanh(x/c), in
 * dBFS; `norm` is the class normalisation gain that restores the cue's loudness after
 * mastering, in dB. `PROGRAM_DB` is the program gain that puts the anchor cue at its LUFS. */
import type { Profile } from './cuesheet.js';

export interface CueCal {
  c: number;
  norm: number;
}

export const PROGRAM_DB: Record<Profile, number> = { speaker: 0, headphones: 0 };
export const CAL: Record<Profile, Record<string, CueCal>> = { speaker: {}, headphones: {} };
