// The audio harness pointed at the PRODUCT (plan §7.4). It bundles tools/harness-entry.ts —
// the product's recipes, per-voice mastering, buses and stems, profile EQ and dynamics.ts — with
// esbuild, runs it in headless Chromium (Playwright, the bundled browser; no `playwright
// install`), renders every cue and a three-minute human-paced scene per output profile with
// OfflineAudioContext, and exits non-zero if any of the eight checks fails. Every number is
// measured at the chain's output; nothing is faked.
//
//   node tools/audio-check.cjs                     # run the checks
//   node tools/audio-check.cjs --write-calibration # also rewrite src/audio/calibration.ts
//   node tools/audio-check.cjs --fresh             # check on the fresh calibration, ignoring the committed file
//   node tools/audio-check.cjs --wav               # also write listening files to OUT_DIR/wav (every cue through each chain)
//
// OUT_DIR (default tools/out) receives metrics.md and results.json. CHROMIUM_PATH optionally
// points at a local Chromium.
const fs = require('fs');
const path = require('path');
const { createRequire } = require('module');

const root = path.resolve(__dirname, '..');
const args = new Set(process.argv.slice(2));
const OUT = process.env.OUT_DIR ?? path.join(__dirname, 'out');

function req(name) {
  for (const base of [root, path.resolve(root, '../..'), '/opt/node22/lib/node_modules']) {
    try {
      return createRequire(path.join(base, 'noop.js'))(name);
    } catch {
      /* try the next place */
    }
  }
  throw new Error(`cannot find ${name}`);
}

const f1 = (v) => (Number.isFinite(v) ? v.toFixed(1) : '—');
const row = (cells) => `| ${cells.join(' | ')} |`;
const table = (head, rows) => [row(head), row(head.map(() => '---')), ...rows.map(row)].join('\n');

(async () => {
  const esbuild = req('esbuild');
  const { chromium } = req('playwright');
  const built = await esbuild.build({
    entryPoints: [path.join(__dirname, 'harness-entry.ts')],
    bundle: true,
    write: false,
    format: 'iife',
    globalName: 'Harness',
    platform: 'browser',
    target: 'es2022',
    logLevel: 'error',
  });
  const code = built.outputFiles[0].text;

  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined }).catch(() => chromium.launch());
  const page = await browser.newPage();
  page.on('pageerror', (e) => console.log('[pageerror]', e.message));
  page.on('console', (m) => {
    if (m.text().startsWith('[harness]')) console.log(m.text());
  });
  await page.goto('about:blank');
  await page.addScriptTag({ content: code });
  const res = await page.evaluate((o) => window.Harness.run(o), { useFresh: args.has('--fresh') || args.has('--write-calibration'), wav: args.has('--wav') });
  await browser.close();

  fs.mkdirSync(OUT, { recursive: true });
  if (args.has('--wav')) {
    for (const [name, b64] of Object.entries(res.wavs)) {
      const file = path.join(OUT, 'wav', name.includes('/') ? `${name}.wav` : `${name}.wav`);
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, Buffer.from(b64, 'base64'));
    }
    console.log(`wrote ${Object.keys(res.wavs).length} listening files to ${path.join(OUT, 'wav')}`);
  }
  delete res.wavs;
  fs.writeFileSync(path.join(OUT, 'results.json'), JSON.stringify(res));

  if (args.has('--write-calibration')) {
    const ids = res.ids;
    const fmt = (p) => ids.map((id) => `    ${JSON.stringify(id)}: { c: ${res.fresh.CAL[p][id].c === null ? 'null' : res.fresh.CAL[p][id].c}, norm: ${res.fresh.CAL[p][id].norm} },`).join('\n');
    const text = `/* GENERATED by tools/audio-check.cjs --write-calibration. Do not edit by hand.
 * Per cue and profile: \`c\` is the ceiling of the per-voice mastering shaper c·tanh(x/c), in
 * dBFS (null: no shaping needed); \`norm\` is the class normalisation gain that restores the cue's
 * loudness after mastering, in dB. \`PROGRAM_DB\` is the program gain that puts the anchor cue at
 * its LUFS (speaker -21, headphones -25). */
import type { Profile } from './cuesheet.js';

export interface CueCal {
  /** shaper ceiling, dBFS; null when the cue already sits inside the profile's headroom */
  c: number | null;
  norm: number;
}

export const PROGRAM_DB: Record<Profile, number> = { speaker: ${res.fresh.PROGRAM_DB.speaker}, headphones: ${res.fresh.PROGRAM_DB.headphones} };

export const CAL: Record<Profile, Record<string, CueCal>> = {
  speaker: {
${fmt('speaker')}
  },
  headphones: {
${fmt('headphones')}
  },
};
`;
    fs.writeFileSync(path.join(root, 'src/audio/calibration.ts'), text);
    console.log('wrote src/audio/calibration.ts');
  }

  const { ANCHOR_LUFS, AMBIENCE_UNDER, TICK_OVER_BED, BALANCE, ECHO, ECHO_EXEMPT } = res.limits;
  const names = res.ids;
  const S = res.alone.speaker, H = res.alone.headphones;

  const recipes = table(
    ['Cue', 'Bus', 'Class', 'Nodes', 'Active ms (sheet max)', 'Speaker ms', 'Raw peak dBFS', 'Active LUFS', 'Momentary max', 'Tail vs head dB', 'Seed spread dB', 'Peak over loudness: raw / headphones / speaker, dB', 'Mastering residual: headphones / speaker, dB'],
    names.map((n) => {
      const m = res.cues[n];
      return [`\`${n}\``, m.bus, m.cls, res.nodes[n], `${m.activeMs.toFixed(0)} (${m.maxLenMs})`, m.speakerActiveMs.toFixed(0), f1(m.peakDb), f1(m.activeLufs), f1(m.momentaryMax), f1(m.tailVsHeadDb), res.spread[n].toFixed(1), `${f1(m.rawPlr)} / ${f1(m.plrHeadphones)} / ${f1(m.plrSpeaker)}`, `${f1(m.resid.headphones)} / ${f1(m.resid.speaker)}`];
    }),
  );
  const through = table(
    ['Cue', 'Speaker: level shift dB', 'Speaker: tail vs head at the output, dB', 'Speaker: non-linear residual dB', 'Speaker: sample peak / true peak dB', 'Headphones: level shift dB', 'Headphones: sample peak / true peak dB'],
    names.map((n) => [`\`${n}\``, f1(S[n].shiftDb), f1(S[n].tailVsHeadDb), f1(S[n].nonlinearDb), `${f1(S[n].peakDb)} / ${f1(S[n].truePeakDb)}`, f1(H[n].shiftDb), `${f1(H[n].peakDb)} / ${f1(H[n].truePeakDb)}`]),
  );
  const sc = res.scenes;
  const scenes = table(
    ['Profile', 'Anchor LUFS', 'Program gain dB', 'Cue stream LUFS', 'Whole mix LUFS', 'Short-term max', 'True peak dBTP', 'Six-cue burst dBTP', 'Limiter max GR dB', 'Limiter over 1 dB', 'Soft-clip samples', 'Bed short-term max (loudest state)', 'Bed under the anchor (range over pond states)'],
    Object.entries(sc).map(([p, s]) => [p, s.target, f1(s.programDb), f1(s.cueLoudness), f1(s.integrated), f1(s.shortTermMax), f1(s.truePeak), f1(s.burstTruePeak), f1(s.limiterGrMax), `${(s.limiterBusy * 100).toFixed(2)} %`, s.clipped, f1(s.bedShortTermMax), `${f1(s.target - s.bedShortTermMax)} to ${f1(s.target - s.bedShortTermMin)} LU`]),
  );
  const beds = table(['Pond state', 'Speaker bed, short-term max LUFS', 'Headphones bed, short-term max LUFS'], Object.keys(sc.speaker.beds).map((k) => [k, f1(sc.speaker.beds[k]), f1(sc.headphones.beds[k])]));
  const stepTable = table(['Step', 'Low-pass Hz', 'Level dB', '300 Hz: designed / measured dB', '3 kHz: designed / measured dB', 'Ramp 10-90 %, ms', 'Click ratio'], res.steps.map((s) => [s.step, s.hz, s.levelDb, `${f1(s.wantedAt300)} / ${f1(s.measuredAt300)}`, `${f1(s.wantedAt3k)} / ${f1(s.measuredAt3k)}`, s.rampMs, s.clickRatio.toFixed(2)]));
  const clockNames = Object.keys(res.overBed);
  const clock = table(['Clock cue', 'Speaker: over the bed, LU', 'Headphones: over the bed, LU'], clockNames.map((n) => [`\`${n}\``, f1(res.overBed[n].speaker), f1(res.overBed[n].headphones)]));
  const cf = res.confusability;
  const rhythm = (r) => (r.length ? r.map((t) => `${t}`).join(' · ') + ' ms' : 'no attack (a swell)');
  const confus = [
    `Rhythm is the onsets in the first 300 ms; timbre is the log-mel pattern of the first 50 ms. Every cue is compared with the six seat signatures it does not carry, and with the cues that can sound at the same moment of the ask unless both belong to one event. A pair with the same rhythm must differ in timbre by at least the bar: the smallest timbre step between two seat signatures of the same rhythm, ${cf.bar.pair}, ${cf.bar.d.toFixed(1)} dB.`,
    '',
    table(['Cue', 'Rhythm (headphones variant)'], Object.entries(cf.rhythms).map(([k, r]) => [`\`${k}\``, rhythm(r)])),
    '',
    table(['Closest same-rhythm pairs with different meanings', 'Timbre distance dB'], cf.closest.map((p) => [p.pair, p.d.toFixed(1)])),
  ].join('\n');
  const c = res.cuesPerMinute;
  const cpm = `The scripted scene (three minutes, five players, human pace, heard from seat 0) plays ${c.all} cues a minute: table ${c.table}, clock ${c.clock}, power ${c.power}, at ${c.asks} asks a minute. ${res.drops.length} cues were refused by the voice pool${res.drops.length ? ` (${res.drops.slice(0, 8).join(', ')})` : ''}.`;

  // ---- the eight checks ----
  const scenesE = Object.entries(sc);
  const echo = names.filter((n) => !ECHO_EXEMPT.includes(n) && S[n].tailVsHeadDb > ECHO);
  const peaks = scenesE.filter(([, s]) => s.truePeak > -1 || s.burstTruePeak > -1 || s.clipped > 0);
  const limiting = scenesE.filter(([, s]) => s.limiterBusy > 0.01);
  const bed = scenesE.filter(([, s]) => s.target - s.bedShortTermMax < AMBIENCE_UNDER[0] || s.target - s.bedShortTermMin > AMBIENCE_UNDER[1]);
  const buried = clockNames.flatMap((n) => ['speaker', 'headphones'].filter((p) => res.overBed[n][p] < TICK_OVER_BED).map((p) => `${n} on ${p} ${f1(res.overBed[n][p])} LU`));
  const balance = names.flatMap((n) => [['speaker', S[n]], ['headphones', H[n]]].filter(([, a]) => Math.abs(a.shiftDb) > BALANCE).map(([p, a]) => `${n} on ${p} ${f1(a.shiftDb)} dB`));
  const SIGNATURE_MS = 1400;
  const long = names.filter((n) => !['mus.start', 'mus.podium'].includes(n) && res.cues[n].activeMs > SIGNATURE_MS).map((n) => `${n} ${res.cues[n].activeMs.toFixed(0)} ms`);
  const stepFail = res.steps.flatMap((s) => [
    Math.abs(s.measuredAt300 - s.wantedAt300) > 0.7 ? `step ${s.step} at 300 Hz: ${f1(s.measuredAt300)} dB, designed ${f1(s.wantedAt300)}` : null,
    Math.abs(s.measuredAt3k - s.wantedAt3k) > 0.7 ? `step ${s.step} at 3 kHz: ${f1(s.measuredAt3k)} dB, designed ${f1(s.wantedAt3k)}` : null,
    s.rampMs < 10 || s.rampMs > 35 ? `step ${s.step} ramp ${s.rampMs} ms` : null,
    s.clickRatio > 1.5 ? `step ${s.step} click ratio ${s.clickRatio.toFixed(2)}` : null,
  ]).filter(Boolean);
  const valleyFail = res.valley.flatMap((v, i) => [
    Math.abs(v.measuredAt - v.designedAt) > 0.08 ? `repeat ${v.k} begins at ${v.measuredAt} s, designed ${v.designedAt} s` : null,
    Math.abs(v.measuredDb - v.designedDb) > 3 ? `repeat ${v.k} is ${f1(v.measuredDb)} dB, designed ${f1(v.designedDb)} dB` : null,
    v.brightnessDb >= (i === 0 ? res.dryBrightness : res.valley[i - 1].brightnessDb) - 0.5 ? `repeat ${v.k} is not darker by at least 0.5 dB than the one before (${f1(v.brightnessDb)} dB)` : null,
  ]).filter(Boolean);
  const check = (fail, text, detail) => `- ${fail.length ? 'FAIL' : 'PASS'} — ${text}${fail.length ? ` (${detail ?? fail.join('; ')})` : ''}.`;
  const checks = [
    check(res.strikes, 'plank grammar: no cue but the seat cues strikes plank A, B or C'),
    check(cf.violations.map((p) => `${p.pair} ${p.d.toFixed(1)} dB`), `confusability: no cue shares a rhythm with a seat signature, or with a cue of another event at the same moment, unless their timbres differ by at least the seat step (${cf.bar.d.toFixed(1)} dB)`),
    check(echo.map((n) => `${n} ${f1(S[n].tailVsHeadDb)} dB`), 'echo budget at the output of the speaker chain: every speaker variant keeps its energy after 250 ms at least 12 dB under its first 250 ms (`mus.*` exempt)'),
    check(peaks.map(([p, s]) => `${p}: scene ${f1(s.truePeak)} dBTP, burst ${f1(s.burstTruePeak)} dBTP, clip ${s.clipped}`), 'peaks: true peak ≤ −1 dBTP in the scene and the six-cue pile-up, and the soft clip never engages'),
    check(limiting.map(([p, s]) => `${p} ${(s.limiterBusy * 100).toFixed(2)} %`), 'headroom: at the anchor level the limiter is above 1 dB of reduction for under 1 % of the scene'),
    check(bed.map(([p, s]) => `${p} ${f1(s.target - s.bedShortTermMax)} to ${f1(s.target - s.bedShortTermMin)} LU under`), `ambience: the bed sits ${AMBIENCE_UNDER[0]}–${AMBIENCE_UNDER[1]} LU under the anchor in every state of the pond`),
    check(buried, `the clock: every Clock cue sounds at least ${TICK_OVER_BED} LU over the bed`),
    check(balance, `balance: the chain moves no cue more than ${BALANCE} dB from its cue-sheet level, on either profile`),
    check(res.breaks, 'the palette: only Shark, Mantis Shrimp and Whale break the frame (a cracked-wood transient, splintering fibres, a hull groan), and all three do'),
    check(long, `duration: every cue lasts at most ${SIGNATURE_MS} ms as rendered, but the tulnic's call and the podium`),
    check(valleyFail, "the tulnic's valley: three repeats, each begins within 80 ms of its design time, is within 3 dB of its designed level, and is darker than the one before"),
    check(stepFail, 'darkening: each ambience step lands within 0.7 dB of its designed level and low-pass at 300 Hz and 3 kHz, in a 10-35 ms ramp, with no click (jump at most 1.5x a steady stretch)'),
  ];
  const stale = res.stale.length ? [`- STALE — the committed src/audio/calibration.ts differs from the fresh calibration in ${res.stale.length} entries (${res.stale.slice(0, 6).join('; ')}${res.stale.length > 6 ? '; …' : ''}). Run \`node tools/audio-check.cjs --write-calibration\`.`] : ['- PASS — the committed calibration matches the fresh one.'];
  const info = [];
  const over = names.filter((n) => res.cues[n].activeMs > res.cues[n].maxLenMs * 1.25 && res.cues[n].maxLenMs < 1500);
  if (over.length) info.push(`Length: ${over.map((n) => `\`${n}\` ${res.cues[n].activeMs.toFixed(0)} ms (sheet ${res.cues[n].maxLenMs})`).join(', ')} run past the sheet's maximum by more than 25 %.`);
  const most = names.slice().sort((a, b) => res.nodes[b] - res.nodes[a]).slice(0, 5);
  info.push(`Nodes: the heaviest cues are ${most.map((n) => `\`${n}\` ${res.nodes[n]}`).join(', ')} (the plan's budget is per hit: ≤ 10 nodes plus the mastering shaper).`);

  const ok = checks.every((l) => l.startsWith('- PASS')) && (res.stale.length === 0 || args.has('--write-calibration') || args.has('--fresh'));
  const md = [
    '## Recipes, and each cue mastered per profile (before the chain)',
    recipes,
    '## Every cue alone through the chain, at the calibrated program gain',
    "Level shift is the chain's effect on the cue's loudness against the same cue with no dynamics. The speaker variant is measured as designed, before the runtime safety fade.",
    through,
    '## The scene through each profile',
    `Program gain is calibrated on one thing only: the anchor cue, \`table.turn\`, sounding at ${ANCHOR_LUFS.speaker} LUFS on speakers and ${ANCHOR_LUFS.headphones} LUFS on headphones (K-weighted over its active span, at the output). The cue stream, the whole mix and the bed are then measured, not set.`,
    scenes,
    beds,
    cpm,
    '## The darkening steps (12, 6 and 1 sets remaining), measured on the ambience stem with a noise and a 300 Hz sine as the input',
    stepTable,
    "## The tulnic's valley, measured on the rendered `mus.start` (headphones variant, before mastering)",
    table(['Repeat', 'Designed start s', 'Measured start s', 'Designed level dB', 'Measured level dB (re the dry gesture)', 'Brightness dB, energy above 1.2 kHz re below (dry: ' + f1(res.dryBrightness) + ')'], res.valley.map((v) => [v.k, v.designedAt, v.measuredAt, v.designedDb, f1(v.measuredDb), f1(v.brightnessDb)])),
    '## The clock over the bed',
    clock,
    '## Confusability',
    confus,
    '## Checks',
    checks.join('\n'),
    stale.join('\n'),
    info.length ? '\n' + info.join('\n\n') : '',
  ].join('\n\n');
  fs.writeFileSync(path.join(OUT, 'metrics.md'), md + '\n');
  console.log(['## Checks', ...checks, ...stale, '', ...info].join('\n'));
  console.log(`\nfull report: ${path.join(OUT, 'metrics.md')}`);
  process.exit(ok ? 0 : 1);
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
